# Numpy Library
### It is general purpose arry processing package. It provides high performance multidimentional array object, and tools for working with these arrays. It is fundamental package for scientific computing with Python. In Python the main difference between array and string is array only contains values coresponding to same Data Types whereas in Lists can contains values coresponding to Different Data Types.

In [3]:
#conda install numpy 
#pip install numpy
import numpy as np

In [5]:
#single Dimensional Array
l1=[1,2,3,4,5]
arr= np.array(l1)

In [8]:
type(arr)

numpy.ndarray

In [9]:
print(arr)

[1 2 3 4 5]


In [10]:
arr.shape

(5,)

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
# Multi dimentional Array
l2=[2,4,6,8,10]
l3=[3,6,9,12,15]

arr = np.array([l1,l2,l3])

In [14]:
arr.shape

(3, 5)

In [13]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [15]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 4,  6,  8],
       [10,  3,  6],
       [ 9, 12, 15]])

In [16]:
arr.shape #to check the shape of the array

(3, 5)

In [17]:
arr.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  2,  4,  6,  8, 10,  3,  6,  9, 12, 15]])

# Indexing [ ]

In [30]:
# Acessing the array element
arr1= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [25]:
arr1[5]

6

In [31]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [36]:
arr2=arr1.reshape(3,5)

In [38]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [41]:
arr2[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [43]:
arr2[1:,1:3]

array([[ 7,  8],
       [12, 13]])

In [44]:
arr2[1:2,2:3]

array([[8]])

In [47]:
arr2[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [14]:
arr3=np.arange(0,10)

In [15]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr3=np.arange(0,10,step=2)

In [6]:
arr3

array([0, 2, 4, 6, 8])

In [9]:
arr3[4:]=100

In [10]:
arr3

array([  0,   2,   4,   6, 100])

In [11]:
np.linspace(1,10,30)

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [17]:
arr4=arr3

In [18]:
arr4[3:]=100

In [19]:
arr4

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [22]:
arr4=arr3.copy()

In [23]:
print(arr3)
arr4[3:]=500
print(arr4)

[  0   1   2 100 100 100 100 100 100 100]
[  0   1   2 500 500 500 500 500 500 500]


In [24]:
print(arr3)

[  0   1   2 100 100 100 100 100 100 100]


In [27]:
###Exploratory Data Analysis
val=2
arr3<=2

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [31]:
val=2
arr3/2

array([ 0. ,  0.5,  1. , 50. , 50. , 50. , 50. , 50. , 50. , 50. ])

In [32]:
val=2
arr3*2

array([  0,   2,   4, 200, 200, 200, 200, 200, 200, 200])

In [33]:
val=2
arr3%2

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
#create array an reshape 
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
a1=np.arange(0,10).reshape(5,2)
a2=np.arange(0,10).reshape(2,5)

In [35]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [40]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
np.ones(4,dtype=float)

array([1., 1., 1., 1.])

In [42]:
np.ones((5,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
#random distribution 
np.random.rand(3,3)

array([[0.59923301, 0.80434558, 0.74344819],
       [0.18114718, 0.17314765, 0.4710368 ],
       [0.10952915, 0.38435758, 0.19745484]])

In [65]:
a_exp=np.random.randn(4,4)

In [66]:
a_exp

array([[ 0.72043191, -1.59297311,  0.89517111, -0.51421976],
       [ 0.34811441, -0.04701521, -1.98339205, -0.17600023],
       [ 0.60850116, -0.71897489, -1.30049839, -0.19260892],
       [-1.38898212,  1.59407464,  0.43990435,  0.90451215]])

In [67]:
import seaborn as sns
import pandas as pd

In [68]:
sns.distplot(pd.DataFrame(a_exp.reshape(16,1)))

TypeError: 'DataFrame' object is not callable

In [51]:
np.random.randint(0,100,8).reshape(4,2)

array([[18, 21],
       [65, 71],
       [28, 95],
       [75, 46]])

In [55]:
np.random.random_sample((1,5))

array([[0.15873263, 0.61958789, 0.75959825, 0.22620437, 0.86537032]])